INSERT INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES
	(65100, 'Peau : %u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65101, 'Visage : %u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65102, 'Cheveux : %u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65103, 'Couleur : %u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65104, 'Pilosite/Details : %u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65105, 'Tatouage : %u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65106, 'Cornes : %u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65107, 'Bandeau : %u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65108, 'Voici les informations concernant vos personnages que vous pouvez mettre dans la forge PNJ !', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65109, '-- EQUIPEMENT --', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65110, 'DisplayID du casque : -%u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65111, 'DisplayID des épaulières : -%u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65112, 'DisplayID de la chemise : -%u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65113, 'DisplayID du torse : -%u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65114, 'DisplayID de la ceinture : -%u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65115, 'DisplayID des jambières : -%u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65116, 'DisplayID des bottes : -%u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65117, 'DisplayID des brassards: -%u', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65118, 'DisplayID des gants: -%u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65119, 'DisplayID de la cape: -%u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65120, 'DisplayID du tabard: -%u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65121, 'ID de l\'arme droite : %u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65122, 'ID de l\'arme gauche : %u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90000, 'Vous venez de créer votre phase !', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90001, 'Oups... Il semblerait que cette ID de phase soit déjà utilisé par quelqu\'un d\'autre. Merci d\'en choisir une autre !', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90002, 'Erreur ! Votre ID de phase doit être supérieur à 5000 et inférieure à 65535.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90003, 'Vous ne pouvez pas créer une phase alors que votre personnage se situe dans une phase.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90004, 'Pour vous y rendre, appliquez la commande suivante ; .phase initialize et téléportez-vous au point suivant : .tel %s !', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90005, 'Le joueur %s vient d\'être invité dans votre phase.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90006, 'Vous n\'êtes pas le propriétaire de cette phase.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90007, 'La Skybox a bien été changée.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90008, 'Malheureusement, la skybox de cette zone ne peut pas être changée.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90009, 'Téléportation réussie avec succès ! Bienvenue.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90010, 'Échec de la téléportation ! Vous n\'êtes pas autorisé(e) de vous téléporter dans cette phase.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90011, 'Phase correctement initialisée.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90012, 'Vous avez été invité dans la phase %u par %s ! Vous pouvez donc à présent vous téléportez dans cette phase.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90013, 'L\'ID de la map que vous souhaitez copié (%u) est invalide. Si vous avez un doute, utilisez la commande .gps', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90014, '|cff01DF86[Annonce de phase] : %s|r', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90025, 'Account : %u n\'a désormais plus les droits pour éxecuter la commande/permission : %u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90021, 'AccountId du spawneur : %u', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90022, 'Guid du spawneur : %u', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90023, 'Nom du spawneur : %s', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90024, 'Le personnage-spawneur a été supprimé, impossible de récupérer le nom. Se fier aux valeurs en dessus (guid et account)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90026, 'Account : %u a déjà plus les droits pour éxecuter la commande/permission : %u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90027, '|cff00F6EE-NOUVELLE REQUÊTE- |cffFE00A1TicketID : |cff00F6EE%u (|cffFE00A1accountId : |cff00F6EE%u, |cffFE00A1playerId : |cff00F6EE%u) |cff00F6EEpar|cff00F6EE %s', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90028, '|cff00F6EEContenu de la requête (|cffFE00A1TicketID : |cff00F6EE%u) : |cff00F6EE%s', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90029, 'Ticket ouvert : TicketID : %u TicketMsg : %s TicketOwner : %s', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65124, 'DisplayID de l\'arme primaire : -%u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65125, 'DisplayID de l\'arme secondaire : -%u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(65126, 'DisplayID de l\'arme tertiaire : -%u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70000, 'La cible n\'est pas une créature. Veuillez sélectionner une créature.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70001, 'Il n\'y a aucun PNJ dans cette Map correspondant à votre GUID de cible %u. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70002, 'MAIL ENVOYE: ID : |cffffffff%u|r, RECEIVER : |cffffffff%s|r, SUBJECT : |cff99FFCC%s|r.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70003, 'MAIL RECU: ID : |cffffffff%u|r, SENDER : |cffffffff%s|r, SUBJECT : |cff99FFCC%s|r.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70004, '  |cffff6666%s|r (%s)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70005, '%u - |cffffffff[%s]|r.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70006, 'Aucune skybox ne correspond.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70007, 'Ambiance light : |cffffffff%u|r - |cffffffff%u|r - |cffffffff%u|r - |cffffffff%u|r - |cffffffff%u|r', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70008, 'Pas d\'ambiance, probablement une map inexistante.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70009, 'Argument invalide.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70010, 'Les ambiances de la Map %s sont : ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70011, '%u - |cffffffff[%s]|r.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70012, 'Pas de son contenant ce mot.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70013, '%u - |cffffffff[%s]|r.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70014, 'Aucune map trouvée.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70015, 'Phase vous appartenant :%s', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70016, 'Vous n\'êtes propriétaire d\'aucune phase.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70017, 'Phase où vous êtes autorisé(e) :%s', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70018, 'Vous n\'êtes autorisé(e) dans aucune phase.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70019, 'Contenu du message : |cff99FFCC%s|r.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70020, 'Aucun mail existant correspondant à cet ID.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70021, 'Le nom rentré n\'est pas conforme aux charactères autorisés.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70022, 'Le nom rentré est trop long, la taille max est de 40 charactères (les espaces comptent).', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70023, 'Parfait ! Votre nouveau nom est |cffffffff%s|r.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90030, '|cff00F6EELe joueur %s (|cffFE00A1accountId : |cff00F6EE%u) a annulé son ticket. (|cffFE00A1TicketID : |cff00F6EE%u)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90033, '|cff00F6EEVous avez annulé votre ticket.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90034, '|cff00F6EECet ID de ticket n\'est pas présent dans la base de donnée.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90035, '|cff00F6EEVous avez déjà annulé ce ticket.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90036, '|cff00F6EETicket non-traîtés : (|cffFE00A1TicketID : |cff00F6EE%u, |cffFE00A1Requête : |cff00F6EE%s, |cffFE00A1Joueur : |cff00F6EE%s, |cffFE00A1AccountID : |cff00F6EE%u, |cffFE00A1PlayerID : |cff00F6EE%u)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90037, '|cff00F6EET\'as de la chance, laideron ! Pas d\'requête ouverte aujourd\'hui pour le moment. Bonne pause.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90038, '|cff00F6EEVos tickets en cours : (|cffFE00A1TicketID : |cff00F6EE%u, |cffFE00A1Requête : |cff00F6EE%s)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90039, '|cff00F6EEVous n\'avez aucun ticket en cours !', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70024, '%u - |cffffffff|Hitem:%u:0:0:0:0:0:0:0:0|h[%s]|h|r, AppID: |cff80ff80%u|r, DisplayID: |cff80ff80%u|r', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90015, 'Vous jouez le Son: %u', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90016, 'Vous n\'êtes pas autorisé(e) à jouer un son en dehors de vos phases et des phases dans lesquelles vous êtes co-propriétaire.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70025, 'Créatures non sauvegardées de votre compte supprimées.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70026, 'Veuillez saisir l\'ID de la phase à supprimer du lookup.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70027, 'Entry : |cffffffff%u|r supprimée.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70028, 'Il n\'existe aucune entry de cet ID vous appartenant.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(70029, 'Vous n\'êtes pas le/la propriétaire de cette phase.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90040, 'Le joueur %s n\'est plus autorisé à se joindre à votre phase.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90041, 'Vous avez été kické de la phase %u par %s. Téléportation au Sanctuaire imminente.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90042, 'Le joueur %s est désormais administrateur de la phase.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90043, 'Vous avez été nommé administrateur de la phase %u par %s. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90044, 'Le joueur %s n\'a plus les droits d\'administration sur cette phase.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90045, 'Vous n\'avez désormais plus aucun droits d\'administration sur la phase %u.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90046, 'Votre phase est désormais en mode privé. Seul les joueurs ayant reçu une invitation pourront joindre celle-ci.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90047, 'Votre phase est désormais en mode publique. Tous les joueurs auront accès à votre phase et pourront se joindre à celle-ci.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90049, 'Veuillez entrer le nom de la race et son sexe dans la commande.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90050, 'Mauvaise combinaison, veuillez utiliser la commande correctement, exemple : .char set race vulpera male.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90051, 'Ceci n\'est pas une classe acceptable, merci de ne pas mettre d\'accent ou de mettre \'dh\' ou \'dk\' pour les chevaliers de la mort ou chasseurs de démons.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(90052, 'veuillez entrer une classe pour changer de classe.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91000, 'Aucune duplication trouvée avec ce nom.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91001, '%u - |cffffffff[%s]|r de %s', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91002, 'Le rayon est trop élevée, veuillez le réduire (maximum : 150)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91003, 'Il y a plus de 1000 gameobjects trouvés avec ce rayon, impossible de créer une duplication.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91004, 'La duplication a été enregistrée ! (ID : %u) (%s) par %s', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91005, 'La duplication (ID : %u) est introuvable.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91006, 'La duplication (ID : %u) est privée, vous n\'y avez pas accès.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91007, 'La duplication à été ajouté !  (GUID : %u) (ID : %u) (Nom : %s) ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91008, 'Aucune duplication trouvé.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91009, 'Une duplication à été trouvé, mais tout les objets associés ont été supprimés manuellement, suppression de la duplication.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91010, 'La duplication la plus proche est trop éloigné pour être affiché.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91011, 'La duplication est a %2.0f cm de vous.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91012, 'La duplication est a %3.2f m de vous.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91013, 'Duplication trouvé: |cffffffff[%s]|r, GUID: %s \r\nID: %u X: %f Y: %f Z: %f MapId: %u', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91014, 'La duplication (Guid : %u) à été supprimé.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91015, 'La duplication (Guid : %u) est introuvable.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91016, 'La duplication (ID : %u) est maintenant privée.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91017, 'La duplication (ID : %u) est maintenant publique.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91018, 'La duplication (ID : %u) à été retiré de la base de données.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91019, 'La duplication (ID : %u) est introuvable ou alors vous n\'en êtes pas le propriétaire.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	(91020, 'Veuillez choisir un nom de duplication contenant 50 caractères ou moins.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);